version: '3.8'
services:
  backend:
    build:
      context: ./backend  # Dockerfile 的构建上下文路径
    container_name: laravel-app
    ports:
      - "8000:8000"  # 映射容器的 8000 端口到本地的 8000 端口
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html 
      - /var/www/html/vendor
      - /var/www/html/node_modules

  frontend:
    build:
      context: ./recipe-app  # Dockerfile 的构建上下文路径
    container_name: react-app
    ports:
      - "3000:3000"  # 映射容器的 3000 端口到本地的 3000 端口
    volumes:
      - ./recipe-app:/app
      - /app/node_modules

  mysql:
    image: mysql:8.1.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: myDBpw
      MYSQL_USER: fsduser
      MYSQL_PASSWORD: myDBpw
      MYSQL_DATABASE: fsd10_tango
    ports:
      - "3308:3306"  # 映射容器的 3306 端口到本地的 3308 端口 local machine 3306 3307 ports are used by other mysql instances

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

